version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_LOG_DESTINATION=stderr
      - POSTGRES_LOGGING_COLLECTOR=on
      - POSTGRES_LOG_DIRECTORY=/var/log/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d admin -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/var/log/postgresql
      - ./db/:/var/lib/postgresql/data
    networks:
      - web_network

  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./src/storage:/src/storage
      - ./src/log:/src/log
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - web_network


  nginx:
    container_name: nginx
    build: ./client
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./src/storage:/app/storage
    networks:
      - web_network
    depends_on:
      - api
    ports:
      - "8080:80"

networks:
  web_network:
    driver: bridge
volumes:
  postgres_data:
  postgres_log: