"""change media

Revision ID: 4ef16e5942c9
Revises: d670a01c81d0
Create Date: 2024-05-20 15:52:52.696761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef16e5942c9'
down_revision: Union[str, None] = 'd670a01c81d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
