"""add extension

Revision ID: 5e3cebe3306e
Revises: 4ef16e5942c9
Create Date: 2024-05-21 13:07:15.567167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e3cebe3306e"
down_revision: Union[str, None] = "4ef16e5942c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media", sa.Column("extension", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "extension")
    # ### end Alembic commands ###
