FROM python:3.9

WORKDIR /src

COPY src/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .

COPY ./.env .

RUN mkdir -p /storage

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]